[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true


ffi = true
gas_reports = ["*"]

# Remappings for cleaner imports
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/"
]

# Profile for testing
[profile.test]
verbosity = 2
gas_reports = ["StrideIntentMatcher", "StrideSwapRouter"]

# Profile for CI
[profile.ci]
verbosity = 4
gas_reports = ["*"]

# Deployment configurations
[invariant]
runs = 256
depth = 15
fail_on_revert = false

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true